export const languages = {
    javascript: { name: 'JavaScript', ext: 'js' },
    typescript: { name: 'TypeScript', ext: 'ts' },
    python: { name: 'Python', ext: 'py' },
    java: { name: 'Java', ext: 'java' },
    cpp: { name: 'C++', ext: 'cpp' },
    c: { name: 'C', ext: 'c' },
    csharp: { name: 'C#', ext: 'cs' },
    php: { name: 'PHP', ext: 'php' },
    ruby: { name: 'Ruby', ext: 'rb' },
    swift: { name: 'Swift', ext: 'swift' },
    kotlin: { name: 'Kotlin', ext: 'kt' },
    go: { name: 'Go', ext: 'go' },
    rust: { name: 'Rust', ext: 'rs' },
    scala: { name: 'Scala', ext: 'scala' },
    dart: { name: 'Dart', ext: 'dart' },
    html: { name: 'HTML', ext: 'html' },
    css: { name: 'CSS', ext: 'css' },
    scss: { name: 'SCSS', ext: 'scss' },
    less: { name: 'Less', ext: 'less' },
    xml: { name: 'XML', ext: 'xml' },
    json: { name: 'JSON', ext: 'json' },
    yaml: { name: 'YAML', ext: 'yml' },
    markdown: { name: 'Markdown', ext: 'md' },
    sql: { name: 'SQL', ext: 'sql' },
    shell: { name: 'Shell Script', ext: 'sh' },
    powershell: { name: 'PowerShell', ext: 'ps1' },
    perl: { name: 'Perl', ext: 'pl' },
    r: { name: 'R', ext: 'r' },
    matlab: { name: 'MATLAB', ext: 'm' },
    lua: { name: 'Lua', ext: 'lua' },
    haskell: { name: 'Haskell', ext: 'hs' },
    elixir: { name: 'Elixir', ext: 'ex' },
    erlang: { name: 'Erlang', ext: 'erl' },
    clojure: { name: 'Clojure', ext: 'clj' },
    groovy: { name: 'Groovy', ext: 'groovy' },
    fortran: { name: 'Fortran', ext: 'f90' },
    cobol: { name: 'COBOL', ext: 'cbl' },
    pascal: { name: 'Pascal', ext: 'pas' },
    ada: { name: 'Ada', ext: 'ada' },
    assembly: { name: 'Assembly', ext: 'asm' },
    vb: { name: 'Visual Basic', ext: 'vb' },
    objectivec: { name: 'Objective-C', ext: 'm' },
    latex: { name: 'LaTeX', ext: 'tex' },
    dockerfile: { name: 'Dockerfile', ext: 'dockerfile' },
    graphql: { name: 'GraphQL', ext: 'graphql' },
    apex: { name: 'Apex', ext: 'cls' },
    vhdl: { name: 'VHDL', ext: 'vhd' },
    verilog: { name: 'Verilog', ext: 'v' },
    coffeescript: { name: 'CoffeeScript', ext: 'coffee' },
    fsharp: { name: 'F#', ext: 'fs' },
    julia: { name: 'Julia', ext: 'jl' },
    prolog: { name: 'Prolog', ext: 'pl' },
    scheme: { name: 'Scheme', ext: 'scm' }
};

export const languageList = Object.keys(languages);